# Generated by Django 2.1.1 on 2019-02-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=120, unique=True)),
                ('issue_date', models.DateField()),
                ('document_type', models.CharField(choices=[('PASS', 'passport'), ('BIRTH', 'birth certificate'), ('STUD', 'student card')], max_length=30)),
                ('scan', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('patr_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=12)),
                ('start_education', models.DateField(auto_now_add=True)),
                ('finish_education', models.DateField()),
                ('education_group', models.CharField(max_length=120)),
                ('education_place', models.CharField(max_length=120)),
            ],
        ),
    ]
