# Generated by Django 2.1.1 on 2019-02-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='documents',
            field=models.ManyToManyField(to='personsapp.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='scan',
            field=models.FileField(upload_to='files/'),
        ),
    ]
