# Generated by Django 2.1.1 on 2019-02-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personsapp', '0004_auto_20190204_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personsapp.Person'),
        ),
    ]
