# Generated by Django 2.1.1 on 2019-02-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personsapp', '0006_auto_20190204_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='personsapp.Person'),
        ),
        migrations.AlterField(
            model_name='document',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='personsapp.Image'),
        ),
    ]
